import { blockIdFromInput, literalFromInput } from './block-input.ts'
import { traverseStack } from './block-traversal.ts'
import type { CompilerServices } from './compiler-types.ts'
import { greenFlagRoots, warnAboutUnsupportedEvents } from './events.ts'
import { pythonLiteral, pythonString, safeIdentifier, uniqueIdentifier } from './python-syntax.ts'
import { reporterConverters } from './reporters.ts'
import { statementConverters } from './statements.ts'
import type { ScratchBlock, ScratchInput, ScratchProject, ScratchTarget } from './types.ts'

const RESERVED_NAMES = new Set([
  'project', 'scratch_number', 'scratch_truth', 'scratch_compare', 'scratch_equals', 'scratch_divide'
])

export class ReadablePythonGenerator {
  readonly warnings = new Set<string>()
  convertedBlockCount = 0
  private readonly project: ScratchProject
  private readonly actorNames = new Map<ScratchTarget, string>()
  private readonly variableNames = new Map<string, string>()
  private readonly moduleNames = new Set(RESERVED_NAMES)

  constructor(project: ScratchProject) {
    this.project = project
    this.assignReadableNames()
  }

  generate(): string {
    const definitions: string[] = []
    let eventCount = 0

    for (const target of this.project.targets) {
      const actor = this.actorNames.get(target) ?? 'project.stage'
      for (const root of greenFlagRoots(target)) {
        eventCount += 1
        this.convertedBlockCount += 1
        const preferred = `${safeIdentifier(target.name, 'stage')}_when_green_flag`
        const functionName = uniqueIdentifier(preferred, this.moduleNames)
        const body = this.compileStack(root.block.next, target, 1, new Set([root.id]))
        definitions.push([
          '@project.when_green_flag',
          `async def ${functionName}():`,
          ...(body.length ? body : ['    pass']),
          ''
        ].join('\n'))
      }
      warnAboutUnsupportedEvents(target, (message) => this.warnings.add(message))
    }

    if (!eventCount) this.warnings.add('No green-flag scripts were found in this project.')
    return [
      '# Generated by Parrot Base V0.3.1.motion from a Scratch 3 project.',
      '# Requires the Parrot Python runtime and this project’s separate asset bundle.',
      '# Edit this file and press Run Python to execute exactly what you see here.',
      '',
      'from parrot import (',
      '    Project,',
      '    scratch_compare,',
      '    scratch_divide,',
      '    scratch_equals,',
      '    scratch_number,',
      '    scratch_truth,',
      ')',
      '',
      'project = Project()',
      ...this.generateDeclarations(),
      '',
      ...definitions,
      'project.run()',
      ''
    ].join('\n')
  }

  private assignReadableNames(): void {
    for (const target of this.project.targets) {
      const preferred = target.isStage ? 'stage' : safeIdentifier(target.name, 'sprite')
      this.actorNames.set(target, uniqueIdentifier(preferred, this.moduleNames))
    }
    for (const target of this.project.targets) {
      for (const [id, definition] of Object.entries(target.variables ?? {})) {
        if (this.variableNames.has(id)) continue
        const preferred = safeIdentifier(String(definition[0] ?? id), 'variable')
        this.variableNames.set(id, uniqueIdentifier(preferred, this.moduleNames))
      }
    }
  }

  private generateDeclarations(): string[] {
    const lines = this.project.targets.map((target) => {
      const name = this.actorNames.get(target) ?? 'stage'
      return target.isStage
        ? `${name} = project.stage`
        : `${name} = project.sprite(${pythonString(target.name)})`
    })

    const variableNameCounts = new Map<string, number>()
    for (const target of this.project.targets) {
      for (const definition of Object.values(target.variables ?? {})) {
        const name = String(definition[0] ?? '')
        variableNameCounts.set(name, (variableNameCounts.get(name) ?? 0) + 1)
      }
    }
    const seen = new Set<string>()
    for (const target of this.project.targets) {
      for (const [id, definition] of Object.entries(target.variables ?? {})) {
        if (seen.has(id)) continue
        seen.add(id)
        const scratchName = String(definition[0] ?? id)
        const owner = variableNameCounts.get(scratchName) === 1 ? '' : `, owner=${pythonString(target.name)}`
        lines.push(`${this.variableNames.get(id)} = project.variable(${pythonString(scratchName)}${owner})`)
      }
    }
    return lines
  }

  private compileStack(startId: string | null, target: ScratchTarget, indent: number, ancestors: Set<string>): string[] {
    return traverseStack({
      startId,
      target,
      ancestors,
      warn: (message) => this.warnings.add(message),
      visit: (block, visited) => this.compileStatement(block, target, indent, visited)
    })
  }

  private services(): CompilerServices {
    return {
      input: (input, target) => this.compileInput(input, target),
      stack: (startId, target, indent, ancestors) => this.compileStack(startId, target, indent, ancestors),
      variable: (id) => this.variableNames.get(id),
      warn: (message) => this.warnings.add(message)
    }
  }

  private compileStatement(block: ScratchBlock, target: ScratchTarget, indent: number, ancestors: Set<string>): string[] {
    const converter = statementConverters[block.opcode]
    if (!converter) {
      this.warnings.add(`Unsupported block ${block.opcode} in ${target.name} was skipped.`)
      const pad = '    '.repeat(indent)
      return [`${pad}# Unsupported Scratch block: ${block.opcode}`, `${pad}pass`]
    }
    this.convertedBlockCount += 1
    return converter({
      block,
      target,
      indent,
      ancestors,
      actor: this.actorNames.get(target) ?? 'project.stage',
      services: this.services()
    })
  }

  private compileInput(input: ScratchInput | undefined, target: ScratchTarget): string {
    const blockId = blockIdFromInput(input)
    if (blockId) {
      const block = target.blocks[blockId]
      if (block) return this.compileReporter(block, target)
    }
    const literal = literalFromInput(input)
    if (literal && typeof literal === 'object' && 'variableId' in literal) {
      const id = String(literal.variableId)
      return `${this.variableNames.get(id) ?? `project.variable_by_id(${pythonString(id)})`}.value`
    }
    return pythonLiteral(literal ?? 0)
  }

  private compileReporter(block: ScratchBlock, target: ScratchTarget): string {
    const converter = reporterConverters[block.opcode]
    if (!converter) {
      this.warnings.add(`Unsupported reporter ${block.opcode} in ${target.name} was replaced with 0.`)
      return '0'
    }
    if (!block.shadow) this.convertedBlockCount += 1
    return converter({
      block,
      target,
      actor: this.actorNames.get(target) ?? 'project.stage',
      services: this.services()
    })
  }
}
